# Generated by Django 2.2.20 on 2021-06-06 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_blog_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
