# Generated by Django 2.2.20 on 2021-06-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default='admin', max_length=50),
            preserve_default=False,
        ),
    ]
